name: fl_upnp
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^9.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_info_plus: ^4.2.0
  sprintf: ^7.0.0
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  test: ^1.24.3

flutter: