on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-warnings

      - name: Test
        run: flutter test --no-pub --test-randomize-ordering-seed random --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.codecov_token }}

      - name: Include in Release
        uses: googleapis/release-please-action@v4.1.1
        with:
          token: ${{ secrets.release_please_token }}
          release-type: dart
